# Generated by Django 5.2.1 on 2025-05-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.route')),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, help_text='Фінішна позиція', null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racer')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
            options={
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='race',
            name='participants',
            field=models.ManyToManyField(related_name='races', through='races.RaceEntry', to='races.racer'),
        ),
    ]
