# Generated by Django 5.2.1 on 2025-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration_from_0_to_100',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='horse_power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='participation_in_races',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='release_date',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='age',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='country',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='family',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='places_of_participation',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='teams',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='country',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='number_of_sectors',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='number_of_turns',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='what_races_are_held',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='year_of_manufacture',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
