# Generated by Django 5.2.1 on 2025-06-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_car_acceleration_from_0_to_100_car_horse_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.racer'),
        ),
    ]
